version: '3.4'


networks:
    monitor_network:
        driver: bridge


services:

    node_exporter:
        image: prom/node-exporter:latest
        container_name: monitor_node_exporter

        networks:
            monitor_network:

    cadvisor:
        image: google/cadvisor:latest
        container_name: monitor_cadvisor

        networks:
            monitor_network:

        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro

    mtail:
        image: jaymedh/docker-mtail
        command: ["--progs", "/progs", "--logs", "/home/test1.log,/home/test2.log"]
        container_name: monitor_mtail

        networks:
            monitor_network:

        ports:
            - published: 3903
              target: 3903
              protocol: tcp

        volumes:
            - type: bind
              source: ./progs
              target: /progs
            - type: bind
              source: ./data
              target: /home
