version: '3.4'


networks:
    monitor_network:
        driver: bridge


volumes:
    prometheus_volume:
    grafana_volume:


services:

    prometheus:
        image: prom/prometheus:latest
        command: [
            "--config.file=/etc/prometheus/prometheus.yml",
            "--storage.tsdb.retention=3d",
            "--web.enable-lifecycle"
            ]
        container_name: monitor_promehteus

        networks:
            monitor_network:

        restart: unless-stopped

        volumes:
            - type: volume
              source: prometheus_volume
              target: /prometheus
            - type: bind
              target: /etc/prometheus
              source: ./config

    alertmanager:
        image: prom/alertmanager
        command: ["--config.file=/etc/alertmanager/alertmanager.yml", "--storage.path=/alertmanager", "--log.level=debug"]
        container_name: monitor_alertmanager

        depends_on:
            - prometheus

        networks:
            monitor_network:

        restart: unless-stopped

        volumes:
            - type: bind
              source: ./config
              target: /etc/alertmanager

    grafana:
        image: grafana/grafana
        container_name: monitor_grafana

        depends_on:
            - prometheus

        environment:
            - GF_SECURITY_ADMIN_USER=mong
            - GF_SECURITY_ADMIN_PASSWORD=passwd

        volumes:
            - type: volume
              source: grafana_volume
              target: /var/lib/grafana
            - type: bind
              source: ./config
              target: /etc/alertmanager

        networks:
            monitor_network:

        restart: unless-stopped

        ports:
            - published: 3000
              target: 3000
              protocol: tcp

    nginx:
        image: library/nginx:alpine
        command: ["nginx", "-c", "/etc/nginx/nginx.conf"]
        container_name: monitor_nginx

        networks:
            monitor_network:

        ports:
            - published: 9090
              target: 9090
              protocol: tcp
            - published: 9093
              target: 9093
              protocol: tcp

        restart: unless-stopped

        volumes:
            - type: bind
              source: ./config
              target: /etc/nginx
