version: '3.4'

services:

    node_exporter:
        image: prom/node-exporter:latest
        container_name: monitor_node_exporter

        networks:
            monitor_network:

    cadvisor:
        image: google/cadvisor:latest
        container_name: monitor_cadvisor

        networks:
            monitor_network:

        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro

