receivers:
    - name: default_receiver
    - name: email_receiver
      email_configs:
          - to: asleea88.app@gmail.com
            from: asleea88.app@gmail.com
            smarthost: smtp.gmail.com:587
            auth_username: asleea88.app@gmail.com
            auth_password: Appapp2011!
            auth_secret: asleea88.app@gmail.com
            auth_identity: asleea88.app@gmail.com
            require_tls: true

route:
    receiver: default_receiver
    group_wait: 1s
    group_interval: 1m
    repeat_interval: 3m
    group_by: [alertname]

    routes:
        - receiver: email_receiver
          match:
              incharge: it-team
